# Generated by Django 4.0.5 on 2022-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='registered_languages',
            field=models.ManyToManyField(to='languages.languages'),
        ),
    ]
